name: quickstart-ai-ml-functions
lang: unknown
lang_version: unknown
git:
  enable: true
codeowners:
  enable: true
renovatebot:
  enable: true
  automerge:
    enable: true
semaphore:
  enable: false
